### ISSUE TITLE
Test input

### ISSUE THREAD

**Issue by ronangaillard** [edge33/AdventOfCode-typescript-template#2]
Hi,

How are we supposed to use `getFirstExpectedResult()` ? Where are we supposed to store the test input ?

Thanks for your work :)

**Comment by ronangaillard** [comment]
My bad, I thought that we could test algorithm against test input given in problem description

**Comment by edge33** [comment]
the test input is stored in the input.txt file,

since for the real input you don't have an expected result  (otherwise you would already know the answer to the puzzle :)) the `getFirstExpectedResult` should trivially return the sample test result provided by the daily description, so that you can use the test runner against the samples.

**Comment by ronangaillard** [comment]
Yes I thought that there was a way to validate your solution using the statement input with the statement solution.

Maybe I'll try to do a PR to add this :)

**Comment by edge33** [comment]
I will mark this as solved, thanks to: https://github.com/edge33/AdventOfCode-typescript-template/pull/4
